[tags]
    dc = "us-east-1"

# OUTPUTS
[outputs]
[outputs.influxdb]
    # The full HTTP endpoint URL for your InfluxDB instance
    url = "http://localhost:8086" # EDIT THIS LINE
    # The target database for metrics. This database must already exist
    database = "coords1" # required.

# [outputs.kafka]
    # URLs of kafka brokers
    # brokers = ["localhost:9092"] # EDIT THIS LINE
    # Kafka topic for producer messages
    # topic = "cvcoords"

[[inputs.kafka_consumer]]
	brokers = ["localhost:9092"]
	topic = "cvcoords"
